import React from 'react';

export default function IndustryGuides() {
  const contentHtml = `<div id="industry-education"><h3 className="text-2xl font-semibold mb-6">Education</h3><article className="p-6 bg-gray-50 dark:bg-gray-700 rounded-xl shadow mb-4"><h4 className="font-medium mb-2">Simple: Create a Quiz</h4><pre className="bg-white dark:bg-gray-800 p-4 rounded overflow-x-auto text-sm"><code>Create a 5-question multiple-choice quiz about the water cycle for a 5th-grade science class. Include an answer key.</code></pre></article></div><div id="industry-engineering" className="mt-8"><h3 className="text-2xl font-semibold mb-6">Engineering</h3><article className="p-6 bg-gray-50 dark:bg-gray-700 rounded-xl shadow mb-4"><h4 className="font-medium mb-2">Simple: Explain a Technical Concept</h4><pre className="bg-white dark:bg-gray-800 p-4 rounded overflow-x-auto text-sm"><code>Explain the concept of 'technical debt' to a non-technical project manager using a home maintenance analogy.</code></pre></article></div><div id="industry-finance" className="mt-8"><h3 className="text-2xl font-semibold mb-6">Finance & Stock Market</h3><p className="text-red-600 dark:text-red-400 mb-4 text-sm">Disclaimer: AI-generated content is informational and not financial advice.</p><article className="p-6 bg-gray-50 dark:bg-gray-700 rounded-xl shadow mb-4"><h4 className="font-medium mb-2">Simple: Summarize Market News</h4><pre className="bg-white dark:bg-gray-800 p-4 rounded overflow-x-auto text-sm"><code>Summarize key financial news and analyst ratings for Apple (AAPL) over the past week in three bullet points, focusing on product announcements and earnings.</code></pre></article></div>`;
  return (
    <section id="industry-guides" className="bg-white dark:bg-gray-800 p-8 rounded-2xl shadow-lg">
      <h2 className="text-3xl font-semibold mb-6">Industry-Specific Guides</h2>
      <div className="prose dark:prose-invert max-w-none" dangerouslySetInnerHTML={{ __html: contentHtml.replace(/\\n/g, '<br />') }} />
    </section>
  );
}